spring:
  application:
    name: auth-service

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://localhost:8888
      name: auth-service
      profile: native
      enabled: true
