spring:
  application:
    name: notification-service

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://localhost:8888
      name: notification-service
      profile: native
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092

  mail:
    host: smtp.gmail.com
    port: 587
    username: eliftuncc03@gmail.com
    password: fcadcufzoyjqexet
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true