spring:
  application:
    name: credit-card-service

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://localhost:8888
      name: credit-card-service
      profile: native
      enabled: true