spring:
  application:
    name: transaction-service

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://localhost:8888
      name: transaction-service
      profile: native
      enabled: true