spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
           - Path=/api/users/**

        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/account/**

        - id: credit-card-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/credit-card/**

        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/auth/**

        - id: transaction-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/transaction/**

        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/payment/**

        - id: notification-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/notification/**