spring:
  application:
    name: payment-service

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://localhost:8888
      name: payment-service
      profile: native
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092